# Generated by Django 5.2.1 on 2025-06-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Acheteur'), ('seller', 'Vendeur')], default='buyer', max_length=20),
        ),
    ]
