# Generated by Django 5.2.1 on 2025-06-23 11:11

from django.db import migrations, models #type: ignore
from django.db.models import DecimalField #type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='annee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
