# Generated by Django 5.2.1 on 2025-06-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_annee_alter_vehicle_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='est_vendu',
            field=models.BooleanField(default=False),
        ),
    ]
